from keyboards.user_menu.user_keyboard import KEYB_SCHEDULE, USER_MENU
from keyboards.shedule_keyboard import kb_schedule
from keyboards.survey_keyboard import kb_start_user_survey, kb_survey_group, kb_survey_subgroup, kb_survey_correct